
import type { Calculator, Category } from '@/lib/types';

export const categories: Category[] = [
 {
    name: "Math",
    slug: "math",
    description: "Solve mathematical problems, from basic to complex.",
    iconName: "Calculator",
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Manage your finances, loans, and investments.",
    iconName: "Landmark",
  },
  {
    name: "Health",
    slug: "health",
    description: "Monitor your health and fitness levels.",
    iconName: "HeartPulse",
  },
  {
    name: "Conversions",
    slug: "conversions",
    description: "Convert between various units of measurement.",
    iconName: "ArrowRightLeft",
  },
  {
    name: "Date & Time",
    slug: "date-time",
    description: "Calculate dates, ages, and time differences.",
    iconName: "CalendarClock",
  },
  {
    name: "Programming",
    slug: "programming",
    description: "Tools for developers and programmers.",
    iconName: "Binary",
  },
  {
    name: "Geometry & Engineering",
    slug: "geometry-engineering",
    description: "Calculators for geometric shapes and engineering principles.",
    iconName: "Triangle",
  },
  {
    name: "Miscellaneous",
    slug: "miscellaneous",
    description: "A collection of other useful calculators.",
    iconName: "Gem",
  },
];

export const calculators: Omit<Calculator, 'component'>[] = [
  // Math & Logic
  {
    slug: 'basic-calculator',
    name: 'Basic Calculator',
    description: 'Perform basic arithmetic operations.',
    category: 'Math',
    iconName: 'Calculator',
    seoTitle: 'Free Online Basic Calculator | Simple 4-Function Math Tool',
    metaDescription: 'A simple and fast online basic calculator for your everyday arithmetic needs. Perform addition, subtraction, multiplication, and division with ease on this free four-function calculator.',
  },
  {
    slug: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Perform advanced scientific calculations.',
    category: 'Math',
    iconName: 'FlaskConical',
    seoTitle: 'Advanced Online Scientific Calculator | Free & Easy to Use',
    metaDescription: 'Perform advanced calculations with our powerful online scientific calculator. Includes functions for trigonometry (sin, cos, tan), logarithms (log), exponents, and more.',
    formula: 'Supports standard math functions like sin, cos, tan, log, sqrt, etc.'
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, increases, and decreases.',
    category: 'Math',
    iconName: 'Percent',
    seoTitle: 'Percentage Calculator | Calculate Percentages, Increases & Decreases',
    metaDescription: 'Easily calculate percentages with our free online percentage calculator. Find percentage of a number, percentage increase or decrease, and solve other common percentage problems.',
  },
  {
    slug: 'fraction-calculator',
    name: 'Fraction Calculator',
    description: 'Add, subtract, multiply, and divide fractions.',
    category: 'Math',
    iconName: 'Pi',
    seoTitle: 'Fraction Calculator | Add, Subtract, Multiply & Divide Fractions',
    metaDescription: 'Our free fraction calculator makes fraction math easy. Add, subtract, multiply, and divide proper and improper fractions, with step-by-step results.',
  },
  {
    slug: 'mixed-number-calculator',
    name: 'Mixed Number Calculator',
    description: 'Work with mixed numbers and fractions.',
    category: 'Math',
    iconName: 'Pi',
    seoTitle: 'Mixed Number Calculator | Solve Mixed Fractions Easily',
    metaDescription: 'A simple calculator for adding, subtracting, multiplying, and dividing mixed numbers and mixed fractions. Get accurate answers with steps.',
  },
  {
    slug: 'ratio-calculator',
    name: 'Ratio Calculator',
    description: 'Simplify and work with ratios.',
    category: 'Math',
    iconName: 'Scale',
    seoTitle: 'Ratio Calculator | Simplify Ratios & Solve Proportions',
    metaDescription: 'Use our online ratio calculator to simplify ratios and find missing values in a proportion. Fast, easy to use, and perfect for students and professionals.',
  },
  {
    slug: 'proportion-calculator',
    name: 'Proportion Calculator',
    description: 'Solve proportions and find missing values.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Proportion Calculator | Solve Proportions & Find Missing Values',
    metaDescription: 'An easy-to-use proportion calculator that helps you solve for the missing value (x) in a proportion. Understand cross-multiplication with step-by-step examples.',
  },
  {
    slug: 'mean-median-mode-calculator',
    name: 'Mean/Median/Mode Calculator',
    description: 'Find the average, middle, and most frequent values.',
    category: 'Math',
    iconName: 'Sigma',
    seoTitle: 'Mean, Median, & Mode Calculator | Find the Average of a Data Set',
    metaDescription: 'Quickly find the mean, median, mode, and range of any data set. Our calculator explains each measure of central tendency to help you understand your data.',
  },
  {
    slug: 'standard-deviation-calculator',
    name: 'Standard Deviation Calculator',
    description: 'Calculate the standard deviation of a data set.',
    category: 'Math',
    iconName: 'Sigma',
    seoTitle: 'Standard Deviation Calculator | Calculate Variance & SD',
    metaDescription: 'A powerful calculator to find the standard deviation, variance, and mean of a sample or population data set. Includes formulas and step-by-step explanations.',
  },
  {
    slug: 'probability-calculator',
    name: 'Probability Calculator',
    description: 'Calculate the probability of events.',
    category: 'Math',
    iconName: 'Beaker',
    seoTitle: 'Probability Calculator | Find the Likelihood of Events',
    metaDescription: 'Calculate the probability of single and multiple events with our easy-to-use probability calculator. Perfect for solving homework problems involving dice, coins, and more.',
  },
  {
    slug: 'permutation-combination-calculator',
    name: 'Permutation & Combination',
    description: 'Calculate permutations and combinations.',
    category: 'Math',
    iconName: 'Sigma',
    seoTitle: 'Permutation & Combination Calculator | nPr & nCr Formulas',
    metaDescription: 'Calculate permutations (nPr) and combinations (nCr) quickly. Our tool helps you understand the key difference: whether the order of selection matters.',
  },
  {
    slug: 'factorial-calculator',
    name: 'Factorial Calculator',
    description: 'Calculate the factorial of a number.',
    category: 'Math',
    iconName: 'Variable',
    formula: 'n!',
    seoTitle: 'Factorial Calculator | Find the Factorial of Any Number (n!)',
    metaDescription: 'An online factorial calculator that quickly finds the factorial (n!) of any non-negative integer. Includes the factorial formula and an explanation of zero factorial.',
  },
  {
    slug: 'lcm-gcd-calculator',
    name: 'LCM & GCD Calculator',
    description: 'Find the Least Common Multiple and Greatest Common Divisor.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'LCM and GCD Calculator | Find Least Common Multiple & Greatest Common Divisor',
    metaDescription: 'Easily calculate the Least Common Multiple (LCM) and Greatest Common Divisor (GCD) of a set of numbers. Our tool explains the methods and their applications.',
  },
  {
    slug: 'square-root-cube-root-calculator',
    name: 'Square/Cube Root Calculator',
    description: 'Calculate square roots and cube roots.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Square Root & Cube Root Calculator | Find √ and ∛',
    metaDescription: 'A simple calculator to find the square root and cube root of any number, including negative numbers. Fast, accurate, and easy to use.',
  },
  {
    slug: 'exponent-power-calculator',
    name: 'Exponent & Power Calculator',
    description: 'Calculate powers and exponents.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Exponent & Power Calculator | Calculate x to the power of y',
    metaDescription: 'Quickly calculate the result of any base raised to the power of any exponent. Handles both positive and negative, integer and fractional exponents.',
  },
  {
    slug: 'logarithm-calculator',
    name: 'Logarithm Calculator',
    description: 'Calculate logarithms with different bases.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Logarithm Calculator (Log) | Calculate Log with Any Base',
    metaDescription: 'An easy-to-use log calculator. Solve for the logarithm of any number with any base, including natural logs (ln) and common logs (log10).',
  },
  {
    slug: 'equation-solver',
    name: 'Equation Solver',
    description: 'Solve linear and quadratic equations.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Equation Solver | Linear & Quadratic Equation Calculator',
    metaDescription: 'Solve linear (ax+b=c) and quadratic (ax²+bx+c=0) equations instantly. Our online tool provides the solution(s) and explains the formulas.',
  },
  {
    slug: 'matrix-calculator',
    name: 'Matrix Calculator',
    description: 'Perform matrix operations.',
    category: 'Math',
    iconName: 'Pi',
    seoTitle: 'Matrix Calculator | Add & Subtract 2x2 Matrices',
    metaDescription: 'A simple matrix calculator for performing addition and subtraction on 2x2 matrices. Enter the matrix values to get an instant result.',
  },
  {
    slug: 'complex-number-calculator',
    name: 'Complex Number Calculator',
    description: 'Perform calculations with complex numbers.',
    category: 'Math',
    iconName: 'Variable',
    seoTitle: 'Complex Number Calculator | Add, Subtract, Multiply, Divide',
    metaDescription: 'Perform arithmetic operations on complex numbers. Add, subtract, multiply, and divide complex numbers in the form a + bi and get instant results.',
  },
  {
    slug: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between Roman numerals and numbers.',
    category: 'Math',
    iconName: 'ArrowRightLeft',
    seoTitle: 'Roman Numeral Converter | Numbers to Roman Numerals',
    metaDescription: 'A fast and accurate Roman numeral converter. Easily translate numbers to Roman numerals and back. Includes conversion rules and examples.',
  },

  // Finance & Money
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Calculate your Equated Monthly Installment.',
    category: 'Finance',
    iconName: 'Landmark',
    formula: 'P * r * (1+r)^n / ((1+r)^n - 1)',
    seoTitle: 'Loan EMI Calculator | Equated Monthly Installment Tool',
    metaDescription: 'Calculate your loan EMI (Equated Monthly Installment) with our free and easy-to-use calculator. See how extra payments can reduce your loan tenure and save you interest.',
  },
  {
    slug: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    description: 'Estimate your monthly mortgage payments.',
    category: 'Finance',
    iconName: 'Home',
    formula: 'P * r * (1+r)^n / ((1+r)^n - 1)',
  },
  {
    slug: 'car-loan-calculator',
    name: 'Car Loan Calculator',
    description: 'Calculate your car loan payments.',
    category: 'Finance',
    iconName: 'Car',
    formula: 'P * r * (1+r)^n / ((1+r)^n - 1)',
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    description: 'Calculate simple interest on a principal amount.',
    category: 'Finance',
    iconName: 'PiggyBank',
    formula: 'P * R * T / 100',
    seoTitle: 'Simple Interest Calculator | SI Formula & Calculation',
    metaDescription: 'Quickly calculate simple interest on your loans or investments. Our free calculator uses the standard SI formula (Principal × Rate × Time) and explains how it works.',
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest over time.',
    category: 'Finance',
    iconName: 'PiggyBank',
    formula: 'A = P(1 + r/n)^(nt)',
    seoTitle: 'Compound Interest Calculator | Daily, Monthly, Yearly',
    metaDescription: 'See how your savings can grow with the power of compound interest. Our calculator projects your investment growth over time and explains the compounding formula.',
  },
  {
    slug: 'savings-calculator',
    name: 'Savings Calculator',
    description: 'Plan your savings goals and growth.',
    category: 'Finance',
    iconName: 'PiggyBank',
    seoTitle: 'Savings Growth Calculator | Future Value Planner',
    metaDescription: 'Project the future value of your savings with our easy-to-use calculator. See how initial deposits, monthly contributions, and interest rates impact your growth.',
  },
  {
    slug: 'retirement-calculator',
    name: 'Retirement Calculator',
    description: 'Estimate your retirement savings needs.',
    category: 'Finance',
    iconName: 'PiggyBank',
    seoTitle: 'Retirement Calculator | How Much Do I Need to Retire?',
    metaDescription: 'Plan for your future with our retirement calculator. Estimate how much you need to save to achieve your retirement goals and see if you are on track.',
  },
  {
    slug: 'investment-return-calculator',
    name: 'Investment Return (ROI) Calculator',
    description: 'Calculate the return on your investments.',
    category: 'Finance',
    iconName: 'AreaChart',
    seoTitle: 'Return on Investment (ROI) Calculator | Investment Profit Tool',
    metaDescription: 'Calculate the Return on Investment (ROI) for any investment. Enter your initial and final values to find the net profit and ROI percentage quickly.',
  },
  {
    slug: 'stock-profit-loss-calculator',
    name: 'Stock Profit/Loss Calculator',
    description: 'Calculate profits or losses from stock trades.',
    category: 'Finance',
    iconName: 'AreaChart',
    seoTitle: 'Stock Profit & Loss Calculator | Calculate Your Trade ROI',
    metaDescription: 'Determine the profit or loss from your stock trades with our easy-to-use calculator. Factor in buy/sell prices, quantity, and commissions to find your true ROI.',
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies with live rates.',
    category: 'Finance',
    iconName: 'Globe',
    seoTitle: 'Currency Converter | Exchange Rates for USD, EUR, INR & More',
    metaDescription: 'A simple currency converter for real-time exchange rates. Convert between major world currencies like USD, EUR, JPY, GBP, INR, and more.',
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    description: 'See how inflation affects purchasing power.',
    category: 'Finance',
    iconName: 'Banknote',
    seoTitle: 'Inflation Calculator | Calculate the Value of Money Over Time',
    metaDescription: 'Use our inflation calculator to see how the purchasing power of money has changed over time. Enter an amount and a year range to see its value today.',
  },
  {
    slug: 'vat-gst-calculator',
    name: 'VAT / GST Calculator',
    description: 'Calculate Value-Added Tax or Goods and Services Tax.',
    category: 'Finance',
    iconName: 'Tag',
    seoTitle: 'VAT & GST Calculator | Add or Remove Tax from a Price',
    metaDescription: 'A fast and free VAT/GST calculator. Easily add tax to a net price or find the pre-tax amount from a gross price. Supports any tax rate for accurate calculations.',
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips for services.',
    category: 'Finance',
    iconName: 'Wallet',
    seoTitle: 'Tip Calculator | Calculate & Split the Bill with Tip',
    metaDescription: 'A quick and easy tip calculator. Determine the tip amount for any bill, adjust the percentage, and split the total cost among any number of people.',
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate the final price after a discount.',
    category: 'Finance',
    iconName: 'Tag',
    seoTitle: 'Discount Calculator | Find the Sale Price After a Discount',
    metaDescription: 'Easily calculate the final price after a discount. Enter the original price and discount percentage to find out how much you will pay and how much you save.',
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    description: 'Calculate your take-home salary.',
    category: 'Finance',
    iconName: 'Briefcase',
    seoTitle: 'Salary Calculator | Calculate Your Take-Home Pay',
    metaDescription: 'Estimate your take-home pay by entering your gross salary, pay period, and tax/deduction rates. See a breakdown of your net income.',
  },
  {
    slug: 'overtime-pay-calculator',
    name: 'Overtime Pay Calculator',
    description: 'Calculate your overtime pay.',
    category: 'Finance',
    iconName: 'Clock',
    seoTitle: 'Overtime Pay Calculator | Calculate Your Overtime Earnings',
    metaDescription: 'Calculate your total pay including overtime. Enter your hourly rate, regular hours, overtime hours, and overtime multiplier to see your complete earnings.',
  },
  {
    slug: 'break-even-point-calculator',
    name: 'Break-even Point Calculator',
    description: 'Find the point where revenue equals costs.',
    category: 'Finance',
    iconName: 'Briefcase',
    seoTitle: 'Break-Even Point Calculator | Find Your Break-Even Analysis',
    metaDescription: 'Determine the break-even point for your business. Enter your fixed costs, variable costs, and price per unit to find out how many units you need to sell.',
  },
  {
    slug: 'business-profit-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate the profit margin for your business.',
    category: 'Finance',
    iconName: 'Briefcase',
    seoTitle: 'Profit Margin Calculator | Gross, Operating & Net Margin',
    metaDescription: 'Calculate the gross, operating, and net profit margins for your business. Understand your profitability with this easy-to-use financial tool.',
  },
  {
    slug: 'credit-card-payoff-calculator',
    name: 'Credit Card Payoff Calculator',
    description: 'Plan how to pay off your credit card debt.',
    category: 'Finance',
    iconName: 'CreditCard',
    seoTitle: 'Credit Card Payoff Calculator | Debt Repayment Planner',
    metaDescription: 'Find out how long it will take to pay off your credit card balance. Enter your balance, APR, and monthly payment to see your payoff schedule and total interest.',
  },

  // Health & Fitness
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index.',
    category: 'Health',
    iconName: 'HeartPulse',
    formula: 'weight (kg) / (height (m) * height (m))',
    tags: ['health', 'fitness', 'weight', 'body mass index'],
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    description: 'Estimate your Basal Metabolic Rate.',
    category: 'Health',
    iconName: 'Scale',
    formula: "Mifflin-St Jeor: 10*weight(kg) + 6.25*height(cm) - 5*age + (gender==='male' ? 5 : -161)",
  },
  {
    slug: 'calorie-needs-calculator',
    name: 'Calorie Needs Calculator',
    description: 'Estimate your daily calorie needs.',
    category: 'Health',
    iconName: 'HeartPulse',
    seoTitle: 'Daily Calorie Needs Calculator | How Many Calories to Eat',
    metaDescription: 'Estimate the number of calories you need to consume daily to maintain your current weight, based on your age, gender, weight, height, and activity level.',
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    description: 'Calculate your ideal body weight.',
    category: 'Health',
    iconName: 'Scale',
    formula: "Robinson Formula (1983)"
  },
  {
    slug: 'body-fat-percentage-calculator',
    name: 'Body Fat Percentage Calculator',
    description: 'Estimate your body fat percentage.',
    category: 'Health',
    iconName: 'Percent',
    formula: "U.S. Navy Method"
  },
  {
    slug: 'lean-body-mass-calculator',
    name: 'Lean Body Mass Calculator',
    description: 'Calculate your lean body mass.',
    category: 'Health',
    iconName: 'Bone',
    seoTitle: 'Lean Body Mass Calculator | Boer Formula',
    metaDescription: 'Estimate your lean body mass (LBM) using the Boer formula. LBM represents the weight of your body minus fat, including muscle, bone, and organs.',
  },
  {
    slug: 'waist-to-hip-ratio-calculator',
    name: 'Waist-to-Hip Ratio Calculator',
    description: 'Calculate your waist-to-hip ratio.',
    category: 'Health',
    iconName: 'Ruler',
    seoTitle: 'Waist-to-Hip Ratio Calculator (WHR) | Health Risk Assessment',
    metaDescription: 'Calculate your Waist-to-Hip Ratio (WHR) to assess your body fat distribution and potential health risks. Learn what your WHR means for your health.',
  },
  {
    slug: 'pregnancy-due-date-calculator',
    name: 'Pregnancy Due Date Calculator',
    description: 'Estimate your pregnancy due date.',
    category: 'Health',
    iconName: 'Baby',
    formula: "Naegele's rule",
    seoTitle: 'Pregnancy Due Date Calculator | Estimate Your Delivery Date',
    metaDescription: 'Get an estimated due date for your baby using your last menstrual period (LMP) or date of conception. Learn about due date calculation methods.',
  },
  {
    slug: 'ovulation-calculator',
    name: 'Ovulation Calculator',
    description: 'Estimate your most fertile days.',
    category: 'Health',
    iconName: 'CalendarClock',
    seoTitle: 'Ovulation Calculator | Find Your Most Fertile Days',
    metaDescription: 'Estimate your fertile window and ovulation date based on your menstrual cycle length. Our ovulation calculator helps you predict your most fertile days to increase your chances of conception.',
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    description: 'Calculate your daily water intake needs.',
    category: 'Health',
    iconName: 'Droplets',
    seoTitle: 'Daily Water Intake Calculator | How Much Water Should I Drink?',
    metaDescription: 'Estimate your recommended daily water intake based on your age, weight, and activity level. Stay hydrated and healthy with our personalized calculation.',
  },
  {
    slug: 'heart-rate-zone-calculator',
    name: 'Heart Rate Zone Calculator',
    description: 'Calculate your target heart rate zones.',
    category: 'Health',
    iconName: 'HeartPulse',
    seoTitle: 'Heart Rate Zone Calculator | Find Your Target Heart Rate',
    metaDescription: 'Determine your target heart rate zones for exercise. Use our calculator to find your optimal training zones for fat burning, cardio, and peak performance.',
  },
  {
    slug: 'vo2-max-calculator',
    name: 'VO₂ Max Calculator',
    description: 'Estimate your maximum oxygen uptake.',
    category: 'Health',
    iconName: 'Wind',
    seoTitle: 'VO₂ Max Calculator | Estimate Your Aerobic Capacity',
    metaDescription: 'Estimate your VO₂ max, a key indicator of your cardiovascular fitness and aerobic endurance. This non-exercise estimation is based on your resting heart rate and age.',
  },
  {
    slug: 'bac-calculator',
    name: 'Blood Alcohol (BAC) Calculator',
    description: 'Estimate your blood alcohol content.',
    category: 'Health',
    iconName: 'TestTube',
    seoTitle: 'Blood Alcohol Content (BAC) Calculator | Widmark Formula',
    metaDescription: 'Estimate your Blood Alcohol Content (BAC) using the Widmark formula. This calculator provides an educational estimate and is not for legal use.',
  },

  // Conversions
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, weight, temperature, etc.',
    category: 'Conversions',
    iconName: 'Ruler',
    seoTitle: 'Universal Unit Converter | Length, Weight, Temp & More',
    metaDescription: 'A versatile online unit converter for a wide range of measurements, including length, weight, temperature, area, volume, and speed. Fast and easy to use.',
  },
  {
    slug: 'data-storage-converter',
    name: 'Data Storage Converter',
    description: 'Convert between KB, MB, GB, TB, and more.',
    category: 'Conversions',
    iconName: 'Database',
    seoTitle: 'Data Storage Converter | Bits, Bytes, KB, MB, GB, TB',
    metaDescription: 'Convert between various units of digital data storage, from bits and bytes to kilobytes (KB), megabytes (MB), gigabytes (GB), and terabytes (TB).',
  },
  {
    slug: 'data-transfer-rate-converter',
    name: 'Data Transfer Rate Converter',
    description: 'Convert between bps, Kbps, Mbps, and more.',
    category: 'Conversions',
    iconName: 'Shuffle',
    seoTitle: 'Data Transfer Rate Converter | Mbps to MB/s & More',
    metaDescription: 'Convert between different data transfer speed units, such as megabits per second (Mbps) to megabytes per second (MB/s). Essential for internet speed and file download calculations.',
  },
  {
    slug: 'time-converter',
    name: 'Time Converter',
    description: 'Convert between seconds, minutes, hours, and days.',
    category: 'Conversions',
    iconName: 'Clock',
    seoTitle: 'Time Converter | Convert Between Time Units',
    metaDescription: 'A simple and fast time converter for converting between various units of time, including seconds, minutes, hours, days, weeks, and years.',
  },
  {
    slug: 'energy-converter',
    name: 'Energy Converter',
    description: 'Convert between joules, calories, kWh, and more.',
    category: 'Conversions',
    iconName: 'Atom',
    seoTitle: 'Energy Converter | Joules, Calories, kWh, & More',
    metaDescription: 'Convert between different units of energy, such as Joules, Kilojoules, calories, Kilocalories (kcal), and Kilowatt-hours (kWh).',
  },
  {
    slug: 'pressure-converter',
    name: 'Pressure Converter',
    description: 'Convert between Pa, bar, psi, and more.',
    category: 'Conversions',
    iconName: 'Cloud',
    seoTitle: 'Pressure Converter | Pa, kPa, bar, psi, atm & More',
    metaDescription: 'Convert between various units of pressure, including Pascal (Pa), Kilopascal (kPa), bar, atmosphere (atm), and pounds per square inch (psi).',
  },
  {
    slug: 'power-converter',
    name: 'Power Converter',
    description: 'Convert between watts, hp, kW, and more.',
    category: 'Conversions',
    iconName: 'Wind',
    seoTitle: 'Power Converter | Watts, Kilowatts (kW), Horsepower (hp)',
    metaDescription: 'A tool for converting between different units of power, such as watts (W), kilowatts (kW), and horsepower (hp).',
  },
  {
    slug: 'angle-converter',
    name: 'Angle Converter',
    description: 'Convert between degrees and radians.',
    category: 'Conversions',
    iconName: 'Ruler',
    seoTitle: 'Angle Converter | Degrees to Radians & Back',
    metaDescription: 'Quickly convert angles between degrees and radians. An essential tool for students and professionals in math, physics, and engineering.',
  },
  {
    slug: 'fuel-efficiency-converter',
    name: 'Fuel Efficiency Converter',
    description: 'Convert between mpg and L/100km.',
    category: 'Conversions',
    iconName: 'Car',
    seoTitle: 'Fuel Efficiency Converter | MPG to L/100km',
    metaDescription: 'Convert fuel efficiency units between Miles Per Gallon (MPG) and Liters per 100 kilometers (L/100km). Useful for comparing vehicle fuel economy.',
  },

  // Date & Time
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate age from date of birth.',
    category: 'Date & Time',
    iconName: 'CalendarClock',
    formula: 'Current Date - Date of Birth',
    seoTitle: 'Age Calculator | How Old Am I? | Calculate Your Age',
    metaDescription: 'Find your exact age in years, months, and days with our easy-to-use online age calculator. Simply enter your date of birth to get your detailed chronological age.',
  },
  {
    slug: 'date-difference-calculator',
    name: 'Date Difference Calculator',
    description: 'Calculate the difference between two dates.',
    category: 'Date & Time',
    iconName: 'CalendarDays',
    formula: "endDate - startDate",
    seoTitle: 'Date Difference Calculator | Find Days Between Dates',
    metaDescription: "Calculate the exact number of years, months, weeks, and days between any two dates. Perfect for finding the duration of projects, events, or time-sensitive tasks.",
  },
  {
    slug: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Count down to a specific date and time.',
    category: 'Date & Time',
    iconName: 'Timer',
    seoTitle: 'Countdown Timer | Online Timer for Events & Deadlines',
    metaDescription: 'Set a countdown to any date and time. Our online timer will track the days, hours, minutes, and seconds remaining until your event.',
  },
  {
    slug: 'time-zone-converter',
    name: 'Time Zone Converter',
    description: 'Convert time between different time zones.',
    category: 'Date & Time',
    iconName: 'Globe2',
    seoTitle: 'Time Zone Converter | Convert Time Between Cities',
    metaDescription: 'Easily convert the time between different time zones around the world. Find the time difference between any two cities instantly.',
  },
  {
    slug: 'world-clock-calculator',
    name: 'World Clock',
    description: 'Calculate time differences between cities.',
    category: 'Date & Time',
    iconName: 'Globe',
    seoTitle: 'World Clock | Current Time in Major Cities',
    metaDescription: 'View the current local time in major cities across the globe. Our world clock provides an easy way to check time differences and plan international calls.',
  },
  {
    slug: 'working-days-calculator',
    name: 'Working Days Calculator',
    description: 'Calculate working days between two dates.',
    category: 'Date & Time',
    iconName: 'Briefcase',
    seoTitle: 'Working Days Calculator | Business Day Counter',
    metaDescription: "Easily calculate the number of working days (business days) between two dates. This tool automatically excludes weekends to give you an accurate count for project planning.",
  },
  {
    slug: 'week-number-calculator',
    name: 'Week Number Calculator',
    description: 'Find the week number for a given date.',
    category: 'Date & Time',
    iconName: 'CalendarDays',
    seoTitle: 'Week Number Calculator | ISO Week Date',
    metaDescription: "Quickly find the week number for any date using different standards, including ISO 8601. An essential tool for scheduling and planning weekly tasks.",
  },
  {
    slug: 'add-subtract-days-calculator',
    name: 'Add/Subtract Days Calculator',
    description: 'Add or subtract days from a date.',
    category: 'Date & Time',
    iconName: 'CalendarClock',
    seoTitle: 'Add or Subtract Days from a Date Calculator',
    metaDescription: "Find a future or past date by adding or subtracting any number of days from a given start date. Perfect for calculating deadlines, follow-ups, and key milestones.",
  },
  {
    slug: 'business-day-calculator',
    name: 'Business Day Calculator',
    description: 'Find the next business day.',
    category: 'Date & Time',
    iconName: 'Briefcase',
    seoTitle: 'Business Day Calculator | Add & Subtract Workdays',
    metaDescription: "Calculate a future date by adding or subtracting a specific number of business days, automatically skipping weekends to ensure accuracy for business deadlines.",
  },

  // Programming & Tech
  {
    slug: 'binary-converter',
    name: 'Binary & Number System Converter',
    description: 'Convert between binary, decimal, hex, and octal.',
    category: 'Programming',
    iconName: 'Binary',
    formula: 'parseInt(num, fromBase).toString(toBase)',
    seoTitle: 'Binary & Number System Converter | Decimal, Hex, Octal',
    metaDescription: 'A versatile number system converter for binary, decimal, hexadecimal, and octal values. Essential for programmers, developers, and computer science students.',
  },
  {
    slug: 'ascii-text-converter',
    name: 'ASCII ↔ Text Converter',
    description: 'Convert between ASCII codes and text.',
    category: 'Programming',
    iconName: 'ArrowRightLeft',
    seoTitle: 'ASCII to Text Converter (and back)',
    metaDescription: 'Easily convert ASCII codes to text characters and text to ASCII values. A simple and instant tool for developers working with character encoding.',
  },
  {
    slug: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings.',
    category: 'Programming',
    iconName: 'Binary',
    seoTitle: 'Base64 Encoder and Decoder | Online Base64 Tool',
    metaDescription: 'A free online tool to encode your data to Base64 or decode a Base64 string back to its original format. Supports UTF-8 for international characters.',
  },
  {
    slug: 'ip-subnet-calculator',
    name: 'IP Subnet Calculator',
    description: 'Calculate IP subnets and networks.',
    category: 'Programming',
    iconName: 'Network',
    seoTitle: 'IP Subnet Calculator | CIDR & Network Address Tool',
    metaDescription: 'An easy-to-use IP subnet calculator for network administrators and IT professionals. Quickly find network addresses, broadcast addresses, subnet masks, and host ranges.',
    formula: 'Network Address = IP Address & Subnet Mask'
  },
  {
    slug: 'crc-hash-generator',
    name: 'CRC-32 Hash Generator',
    description: 'Generate a CRC-32 checksum for your text input.',
    category: 'Programming',
    iconName: 'Hash',
    seoTitle: 'CRC-32 Hash Generator | Online Checksum Tool',
    metaDescription: 'Generate a CRC-32 hash (checksum) for any string or text input. Our free online tool helps you verify data integrity quickly and easily.',
  },
  {
    slug: 'file-size-calculator',
    name: 'File Size Calculator',
    description: 'Calculate file size from bitrate and duration.',
    category: 'Programming',
    iconName: 'FileBox',
    seoTitle: 'File Size Calculator | Estimate Download & Upload Size',
    metaDescription: 'Estimate the size of a file based on its duration and bitrate. Useful for video, audio, and other media files to plan for storage and bandwidth.',
  },
  {
    slug: 'color-converter',
    name: 'Color Code Converter',
    description: 'Convert between HEX, RGB, and HSL color codes.',
    category: 'Programming',
    iconName: 'Palette',
    seoTitle: 'Color Code Converter | HEX, RGB, HSL',
    metaDescription: 'A simple and intuitive tool for web designers and developers to convert between HEX, RGB, and HSL color formats in real-time.',
  },

  // Geometry & Engineering
  {
    slug: 'circle-calculator',
    name: 'Circle Calculator',
    description: 'Calculate the area and circumference of a circle.',
    category: 'Geometry & Engineering',
    iconName: 'Circle',
    seoTitle: 'Circle Calculator | Find Area, Circumference, Diameter',
    metaDescription: 'A versatile circle calculator. Enter the radius, diameter, circumference, or area to find the other three properties instantly. Includes formulas and explanations.',
  },
  {
    slug: 'triangle-area-calculator',
    name: 'Triangle Area & Perimeter',
    description: 'Calculate the area and perimeter of a triangle.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
    seoTitle: 'Triangle Area & Perimeter Calculator | Heron\'s Formula',
    metaDescription: 'Calculate the area and perimeter of a triangle using various methods, including Base & Height, Heron\'s formula (3 sides), and Side-Angle-Side (SAS).',
  },
  {
    slug: 'rectangle-area-calculator',
    name: 'Rectangle Area & Perimeter',
    description: 'Calculate the area of a rectangle or square.',
    category: 'Geometry & Engineering',
    iconName: 'Ruler',
    formula: "Area = Length * Width"
  },
  {
    slug: 'cylinder-volume-calculator',
    name: 'Cylinder Volume Calculator',
    description: 'Calculate the volume of a cylinder.',
    category: 'Geometry & Engineering',
    iconName: 'Beaker',
    seoTitle: 'Cylinder Volume & Surface Area Calculator',
    metaDescription: 'Calculate the volume, lateral area, base area, and total surface area of a cylinder. Simply enter the radius and height. Includes the formulas used.',
  },
  {
    slug: 'sphere-volume-surface-area-calculator',
    name: 'Sphere Volume & Surface Area',
    description: 'Calculate the volume and surface area of a sphere.',
    category: 'Geometry & Engineering',
    iconName: 'Globe',
    seoTitle: 'Sphere Volume & Surface Area Calculator',
    metaDescription: 'Quickly calculate the volume and surface area of a sphere by providing its radius. Our calculator uses the standard geometric formulas for accurate results.',
  },
  {
    slug: 'cone-volume-calculator',
    name: 'Cone Volume Calculator',
    description: 'Calculate the volume of a cone.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
    seoTitle: 'Cone Volume & Surface Area Calculator',
    metaDescription: 'Easily calculate the volume, slant height, and total surface area of a cone. Just enter the radius and height to get instant results with formulas.',
  },
  {
    slug: 'pythagorean-theorem-calculator',
    name: 'Pythagorean Theorem Calculator',
    description: 'Solve for sides of a right triangle.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
    formula: 'a² + b² = c²',
    seoTitle: 'Pythagorean Theorem Calculator | Solve for a, b, or c',
    metaDescription: 'Easily solve for the missing side of a right-angled triangle using the Pythagorean theorem (a² + b² = c²). Find the hypotenuse or either of the other two sides.',
  },
  {
    slug: 'trigonometry-calculator',
    name: 'Trigonometry Calculator',
    description: 'Calculate sin, cos, tan, and more.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
    seoTitle: 'Trigonometry Calculator | Sin, Cos, Tan & Inverse',
    metaDescription: 'A free trigonometry calculator to find the sine, cosine, tangent, and their inverses (asin, acos, atan) for any angle in degrees or radians. Perfect for students and engineers.',
  },
  {
    slug: 'beam-deflection-calculator',
    name: 'Beam Deflection Calculator',
    description: 'Calculate the deflection of beams.',
    category: 'Geometry & Engineering',
    iconName: 'Ruler',
    seoTitle: 'Beam Deflection Calculator | Cantilever Beams',
    metaDescription: 'A simple calculator to find the maximum deflection of a cantilever beam with a point load at the end. An essential tool for structural engineers.',
  },
  {
    slug: 'torque-calculator',
    name: 'Torque Calculator',
    description: 'Calculate torque from force and distance.',
    category: 'Geometry & Engineering',
    iconName: 'Wind',
    seoTitle: 'Torque Calculator | Force x Distance',
    metaDescription: 'Calculate the resulting torque by entering the force and distance (lever arm length). An easy-to-use tool for physics and engineering students.',
  },
  {
    slug: 'ohms-law-calculator',
    name: 'Ohm’s Law Calculator',
    description: 'Calculate voltage, current, and resistance.',
    category: 'Geometry & Engineering',
    iconName: 'Atom',
    seoTitle: 'Ohm\'s Law Calculator | Voltage, Current, Resistance & Power',
    metaDescription: 'An easy-to-use Ohm\'s law calculator to solve for voltage (V), current (I), resistance (R), and power (P). Enter any two values to find the other two. Essential tool for electronics.',
    formula: 'V = I × R'
  },
  {
    slug: 'resistor-color-code-calculator',
    name: 'Resistor Color Code Calculator',
    description: 'Determine resistor values from color codes.',
    category: 'Geometry & Engineering',
    iconName: 'Palette',
    seoTitle: '4-Band Resistor Color Code Calculator | Find Resistance Value',
    metaDescription: 'A simple tool to decode 4-band resistor color codes. Select the colors for each band to instantly find the resistance value and tolerance.',
  },
  {
    slug: 'capacitor-charge-calculator',
    name: 'Capacitor Charge Calculator',
    description: 'Calculate capacitor charge and discharge times.',
    category: 'Geometry & Engineering',
    iconName: 'Atom',
    seoTitle: 'Capacitor Charging Calculator (RC Circuit)',
    metaDescription: 'Calculate the charge and current in a charging RC (resistor-capacitor) circuit at a specific point in time. An essential tool for electronics.',
  },

  // Education & Miscellaneous
  {
    slug: 'gpa-calculator',
    name: 'GPA Calculator',
    description: 'Calculate your Grade Point Average.',
    category: 'Miscellaneous',
    iconName: 'GraduationCap',
    formula: 'Σ(Grade Points * Credits) / Σ(Credits)'
  },
  {
    slug: 'grade-percentage-calculator',
    name: 'Grade Percentage Calculator',
    description: 'Calculate your grade percentage.',
    category: 'Miscellaneous',
    iconName: 'Percent',
  },
  {
    slug: 'reading-time-calculator',
    name: 'Reading Time Calculator',
    description: 'Estimate the time it takes to read a text.',
    category: 'Miscellaneous',
    iconName: 'Book',
  },
  {
    slug: 'typing-speed-calculator',
    name: 'Typing Speed (WPM) Calculator',
    description: 'Measure your words per minute typing speed.',
    category: 'Miscellaneous',
    iconName: 'Keyboard',
    seoTitle: 'Typing Speed Test (WPM) | Check Your Words Per Minute',
    metaDescription: 'Test your typing speed and accuracy with our free Words Per Minute (WPM) calculator. Practice with sample texts and get instant results.',
  },
  {
    slug: 'loan-affordability-calculator',
    name: 'Loan Affordability Calculator',
    description: 'Estimate how much loan you can afford.',
    category: 'Miscellaneous',
    iconName: 'Landmark',
    seoTitle: 'Loan Affordability Calculator | How Much Can I Borrow?',
    metaDescription: 'Estimate how much you can afford to borrow for a loan based on your income, monthly debts, and the desired loan terms. Perfect for home or car loan planning.',
  },
  {
    slug: 'carbon-footprint-calculator',
    name: 'Carbon Footprint Calculator',
    description: 'Estimate your environmental impact.',
    category: 'Miscellaneous',
    iconName: 'Footprints',
  },
  {
    slug: 'pet-age-calculator',
    name: 'Pet Age Calculator',
    description: 'Calculate your pet\'s age in human years.',
    category: 'Miscellaneous',
    iconName: 'Dog',
    seoTitle: 'Pet Age Calculator | Dog & Cat Years to Human Years',
    metaDescription: 'How old is your pet in human years? Use our pet age calculator to convert your dog or cat\'s age into an equivalent human age.',
  },
];


export const getCalculatorBySlug = (slug: string): Omit<Calculator, 'component'> | undefined => {
  return calculators.find((calculator) => calculator.slug === slug);
};

export const getCalculatorsByCategory = (categorySlug: string) => {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return calculators.filter(c => c.category === category.name);
}
