import type { Calculator, Category } from '@/lib/types';

export const categories: Category[] = [
 {
    name: "Math",
    slug: "math",
    description: "Solve mathematical problems, from basic to complex.",
    iconName: "Calculator",
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Manage your finances, loans, and investments.",
    iconName: "Landmark",
  },
  {
    name: "Health",
    slug: "health",
    description: "Monitor your health and fitness levels.",
    iconName: "HeartPulse",
  },
  {
    name: "Conversions",
    slug: "conversions",
    description: "Convert between various units of measurement.",
    iconName: "ArrowRightLeft",
  },
  {
    name: "Date & Time",
    slug: "date-time",
    description: "Calculate dates, ages, and time differences.",
    iconName: "CalendarClock",
  },
  {
    name: "Programming",
    slug: "programming",
    description: "Tools for developers and programmers.",
    iconName: "Binary",
  },
  {
    name: "Geometry & Engineering",
    slug: "geometry-engineering",
    description: "Calculators for geometric shapes and engineering principles.",
    iconName: "Triangle",
  },
  {
    name: "Miscellaneous",
    slug: "miscellaneous",
    description: "A collection of other useful calculators.",
    iconName: "Gem",
  },
];

export const calculators: Omit<Calculator, 'component'>[] = [
  // Math & Logic
  {
    slug: 'basic-calculator',
    name: 'Basic Calculator',
    description: 'Perform basic arithmetic operations.',
    category: 'Math',
    iconName: 'Calculator',
    seoTitle: 'Free Online Basic Calculator | Simple 4-Function Math Tool',
    metaDescription: 'A simple and fast online basic calculator for your everyday arithmetic needs. Perform addition, subtraction, multiplication, and division with ease on this free four-function calculator.',
  },
  {
    slug: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Perform advanced scientific calculations.',
    category: 'Math',
    iconName: 'FlaskConical',
    seoTitle: 'Advanced Online Scientific Calculator | Free & Easy to Use',
    metaDescription: 'Perform advanced calculations with our powerful online scientific calculator. Includes functions for trigonometry (sin, cos, tan), logarithms (log), exponents, and more.',
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, increases, and decreases.',
    category: 'Math',
    iconName: 'Percent',
    seoTitle: 'Percentage Calculator | Calculate Percentages, Increases & Decreases',
    metaDescription: 'Easily calculate percentages with our free online percentage calculator. Find percentage of a number, percentage increase or decrease, and solve other common percentage problems.',
  },
  {
    slug: 'fraction-calculator',
    name: 'Fraction Calculator',
    description: 'Add, subtract, multiply, and divide fractions.',
    category: 'Math',
    iconName: 'Pi',
    seoTitle: 'Fraction Calculator | Add, Subtract, Multiply & Divide Fractions',
    metaDescription: 'Our free fraction calculator makes fraction math easy. Add, subtract, multiply, and divide proper and improper fractions, with step-by-step results.',
  },
  {
    slug: 'mixed-number-calculator',
    name: 'Mixed Number Calculator',
    description: 'Work with mixed numbers and fractions.',
    category: 'Math',
    iconName: 'Pi',
    seoTitle: 'Mixed Number Calculator | Solve Mixed Fractions Easily',
    metaDescription: 'A simple calculator for adding, subtracting, multiplying, and dividing mixed numbers and mixed fractions. Get accurate answers with steps.',
  },
  {
    slug: 'ratio-calculator',
    name: 'Ratio Calculator',
    description: 'Simplify and work with ratios.',
    category: 'Math',
    iconName: 'Scale',
    seoTitle: 'Ratio Calculator | Simplify Ratios & Solve Proportions',
    metaDescription: 'Use our online ratio calculator to simplify ratios and find missing values in a proportion. Fast, easy to use, and perfect for students and professionals.',
  },
  {
    slug: 'proportion-calculator',
    name: 'Proportion Calculator',
    description: 'Solve proportions and find missing values.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'mean-median-mode-calculator',
    name: 'Mean/Median/Mode Calculator',
    description: 'Find the average, middle, and most frequent values.',
    category: 'Math',
    iconName: 'Sigma',
  },
  {
    slug: 'standard-deviation-calculator',
    name: 'Standard Deviation Calculator',
    description: 'Calculate the standard deviation of a data set.',
    category: 'Math',
    iconName: 'Sigma',
  },
  {
    slug: 'probability-calculator',
    name: 'Probability Calculator',
    description: 'Calculate the probability of events.',
    category: 'Math',
    iconName: 'Beaker',
  },
  {
    slug: 'permutation-combination-calculator',
    name: 'Permutation & Combination',
    description: 'Calculate permutations and combinations.',
    category: 'Math',
    iconName: 'Sigma',
  },
  {
    slug: 'factorial-calculator',
    name: 'Factorial Calculator',
    description: 'Calculate the factorial of a number.',
    category: 'Math',
    iconName: 'Variable',
    formula: 'n!'
  },
  {
    slug: 'lcm-gcd-calculator',
    name: 'LCM & GCD Calculator',
    description: 'Find the Least Common Multiple and Greatest Common Divisor.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'square-root-cube-root-calculator',
    name: 'Square/Cube Root Calculator',
    description: 'Calculate square roots and cube roots.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'exponent-power-calculator',
    name: 'Exponent & Power Calculator',
    description: 'Calculate powers and exponents.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'logarithm-calculator',
    name: 'Logarithm Calculator',
    description: 'Calculate logarithms with different bases.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'equation-solver',
    name: 'Equation Solver',
    description: 'Solve linear and quadratic equations.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'matrix-calculator',
    name: 'Matrix Calculator',
    description: 'Perform matrix operations.',
    category: 'Math',
    iconName: 'Pi',
  },
  {
    slug: 'complex-number-calculator',
    name: 'Complex Number Calculator',
    description: 'Perform calculations with complex numbers.',
    category: 'Math',
    iconName: 'Variable',
  },
  {
    slug: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between Roman numerals and numbers.',
    category: 'Math',
    iconName: 'ArrowRightLeft',
  },

  // Finance & Money
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Calculate your Equated Monthly Installment.',
    category: 'Finance',
    iconName: 'Landmark',
    formula: 'P * r * (1+r)^n / ((1+r)^n - 1)',
  },
  {
    slug: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    description: 'Estimate your monthly mortgage payments.',
    category: 'Finance',
    iconName: 'Home',
  },
  {
    slug: 'car-loan-calculator',
    name: 'Car Loan Calculator',
    description: 'Calculate your car loan payments.',
    category: 'Finance',
    iconName: 'Car',
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    description: 'Calculate simple interest on a principal amount.',
    category: 'Finance',
    iconName: 'PiggyBank',
    formula: 'P * R * T / 100'
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest over time.',
    category: 'Finance',
    iconName: 'PiggyBank',
    formula: 'A = P(1 + r/n)^(nt)'
  },
  {
    slug: 'savings-calculator',
    name: 'Savings Calculator',
    description: 'Plan your savings goals and growth.',
    category: 'Finance',
    iconName: 'PiggyBank',
  },
  {
    slug: 'retirement-calculator',
    name: 'Retirement Calculator',
    description: 'Estimate your retirement savings needs.',
    category: 'Finance',
    iconName: 'PiggyBank',
  },
  {
    slug: 'investment-return-calculator',
    name: 'Investment Return (ROI) Calculator',
    description: 'Calculate the return on your investments.',
    category: 'Finance',
    iconName: 'AreaChart',
  },
  {
    slug: 'stock-profit-loss-calculator',
    name: 'Stock Profit/Loss Calculator',
    description: 'Calculate profits or losses from stock trades.',
    category: 'Finance',
    iconName: 'AreaChart',
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies with live rates.',
    category: 'Finance',
    iconName: 'Globe',
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    description: 'See how inflation affects purchasing power.',
    category: 'Finance',
    iconName: 'Banknote',
  },
  {
    slug: 'vat-gst-calculator',
    name: 'VAT / GST Calculator',
    description: 'Calculate Value-Added Tax or Goods and Services Tax.',
    category: 'Finance',
    iconName: 'Tag',
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips for services.',
    category: 'Finance',
    iconName: 'Wallet',
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate the final price after a discount.',
    category: 'Finance',
    iconName: 'Tag',
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    description: 'Calculate your take-home salary.',
    category: 'Finance',
    iconName: 'Briefcase',
  },
  {
    slug: 'overtime-pay-calculator',
    name: 'Overtime Pay Calculator',
    description: 'Calculate your overtime pay.',
    category: 'Finance',
    iconName: 'Clock',
  },
  {
    slug: 'break-even-point-calculator',
    name: 'Break-even Point Calculator',
    description: 'Find the point where revenue equals costs.',
    category: 'Finance',
    iconName: 'Briefcase',
  },
  {
    slug: 'business-profit-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate the profit margin for your business.',
    category: 'Finance',
    iconName: 'Briefcase',
  },
  {
    slug: 'credit-card-payoff-calculator',
    name: 'Credit Card Payoff Calculator',
    description: 'Plan how to pay off your credit card debt.',
    category: 'Finance',
    iconName: 'CreditCard',
  },

  // Health & Fitness
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate your Body Mass Index.',
    category: 'Health',
    iconName: 'HeartPulse',
    formula: 'weight (kg) / (height (m) * height (m))',
    tags: ['health', 'fitness', 'weight', 'body mass index'],
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    description: 'Estimate your Basal Metabolic Rate.',
    category: 'Health',
    iconName: 'Scale',
    formula: "Mifflin-St Jeor: 10*weight(kg) + 6.25*height(cm) - 5*age + (gender==='male' ? 5 : -161)",
  },
  {
    slug: 'calorie-needs-calculator',
    name: 'Calorie Needs Calculator',
    description: 'Estimate your daily calorie needs.',
    category: 'Health',
    iconName: 'HeartPulse',
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    description: 'Calculate your ideal body weight.',
    category: 'Health',
    iconName: 'Scale',
    formula: "Robinson Formula (1983)"
  },
  {
    slug: 'body-fat-percentage-calculator',
    name: 'Body Fat Percentage Calculator',
    description: 'Estimate your body fat percentage.',
    category: 'Health',
    iconName: 'Percent',
    formula: "U.S. Navy Method"
  },
  {
    slug: 'lean-body-mass-calculator',
    name: 'Lean Body Mass Calculator',
    description: 'Calculate your lean body mass.',
    category: 'Health',
    iconName: 'Bone',
  },
  {
    slug: 'waist-to-hip-ratio-calculator',
    name: 'Waist-to-Hip Ratio Calculator',
    description: 'Calculate your waist-to-hip ratio.',
    category: 'Health',
    iconName: 'Ruler',
  },
  {
    slug: 'pregnancy-due-date-calculator',
    name: 'Pregnancy Due Date Calculator',
    description: 'Estimate your pregnancy due date.',
    category: 'Health',
    iconName: 'Baby',
    formula: "Naegele's rule"
  },
  {
    slug: 'ovulation-calculator',
    name: 'Ovulation Calculator',
    description: 'Estimate your most fertile days.',
    category: 'Health',
    iconName: 'CalendarClock',
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    description: 'Calculate your daily water intake needs.',
    category: 'Health',
    iconName: 'Droplets',
  },
  {
    slug: 'heart-rate-zone-calculator',
    name: 'Heart Rate Zone Calculator',
    description: 'Calculate your target heart rate zones.',
    category: 'Health',
    iconName: 'HeartPulse',
  },
  {
    slug: 'vo2-max-calculator',
    name: 'VO₂ Max Calculator',
    description: 'Estimate your maximum oxygen uptake.',
    category: 'Health',
    iconName: 'Wind',
  },
  {
    slug: 'bac-calculator',
    name: 'Blood Alcohol (BAC) Calculator',
    description: 'Estimate your blood alcohol content.',
    category: 'Health',
    iconName: 'TestTube',
  },

  // Conversions
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert length, weight, temperature, etc.',
    category: 'Conversions',
    iconName: 'Ruler',
  },
  {
    slug: 'data-storage-converter',
    name: 'Data Storage Converter',
    description: 'Convert between KB, MB, GB, TB, and more.',
    category: 'Conversions',
    iconName: 'Database',
  },
  {
    slug: 'data-transfer-rate-converter',
    name: 'Data Transfer Rate Converter',
    description: 'Convert between bps, Kbps, Mbps, and more.',
    category: 'Conversions',
    iconName: 'Shuffle',
  },
  {
    slug: 'time-converter',
    name: 'Time Converter',
    description: 'Convert between seconds, minutes, hours, and days.',
    category: 'Conversions',
    iconName: 'Clock',
  },
  {
    slug: 'energy-converter',
    name: 'Energy Converter',
    description: 'Convert between joules, calories, kWh, and more.',
    category: 'Conversions',
    iconName: 'Atom',
  },
  {
    slug: 'pressure-converter',
    name: 'Pressure Converter',
    description: 'Convert between Pa, bar, psi, and more.',
    category: 'Conversions',
    iconName: 'Cloud',
  },
  {
    slug: 'power-converter',
    name: 'Power Converter',
    description: 'Convert between watts, hp, kW, and more.',
    category: 'Conversions',
    iconName: 'Wind',
  },
  {
    slug: 'angle-converter',
    name: 'Angle Converter',
    description: 'Convert between degrees and radians.',
    category: 'Conversions',
    iconName: 'Ruler',
  },
  {
    slug: 'fuel-efficiency-converter',
    name: 'Fuel Efficiency Converter',
    description: 'Convert between mpg and L/100km.',
    category: 'Conversions',
    iconName: 'Car',
  },

  // Date & Time
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate age from date of birth.',
    category: 'Date & Time',
    iconName: 'CalendarClock',
    formula: 'Current Date - Date of Birth',
  },
  {
    slug: 'date-difference-calculator',
    name: 'Date Difference Calculator',
    description: 'Calculate the difference between two dates.',
    category: 'Date & Time',
    iconName: 'CalendarDays',
    formula: "endDate - startDate"
  },
  {
    slug: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Count down to a specific date and time.',
    category: 'Date & Time',
    iconName: 'Timer',
  },
  {
    slug: 'time-zone-converter',
    name: 'Time Zone Converter',
    description: 'Convert time between different time zones.',
    category: 'Date & Time',
    iconName: 'Globe2',
  },
  {
    slug: 'world-clock-calculator',
    name: 'World Clock',
    description: 'Calculate time differences between cities.',
    category: 'Date & Time',
    iconName: 'Globe',
  },
  {
    slug: 'working-days-calculator',
    name: 'Working Days Calculator',
    description: 'Calculate working days between two dates.',
    category: 'Date & Time',
    iconName: 'Briefcase',
  },
  {
    slug: 'week-number-calculator',
    name: 'Week Number Calculator',
    description: 'Find the week number for a given date.',
    category: 'Date & Time',
    iconName: 'CalendarDays',
  },
  {
    slug: 'add-subtract-days-calculator',
    name: 'Add/Subtract Days Calculator',
    description: 'Add or subtract days from a date.',
    category: 'Date & Time',
    iconName: 'CalendarClock',
  },
  {
    slug: 'business-day-calculator',
    name: 'Business Day Calculator',
    description: 'Find the next business day.',
    category: 'Date & Time',
    iconName: 'Briefcase',
  },

  // Programming & Tech
  {
    slug: 'binary-converter',
    name: 'Binary & Number System Converter',
    description: 'Convert between binary, decimal, hex, and octal.',
    category: 'Programming',
    iconName: 'Binary',
    formula: 'parseInt(num, fromBase).toString(toBase)'
  },
  {
    slug: 'ascii-text-converter',
    name: 'ASCII ↔ Text Converter',
    description: 'Convert between ASCII codes and text.',
    category: 'Programming',
    iconName: 'ArrowRightLeft',
  },
  {
    slug: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings.',
    category: 'Programming',
    iconName: 'Binary',
  },
  {
    slug: 'ip-subnet-calculator',
    name: 'IP Subnet Calculator',
    description: 'Calculate IP subnets and networks.',
    category: 'Programming',
    iconName: 'Network',
  },
  {
    slug: 'crc-hash-generator',
    name: 'CRC-32 Hash Generator',
    description: 'Generate a CRC-32 checksum for your text input.',
    category: 'Programming',
    iconName: 'Hash',
  },
  {
    slug: 'file-size-calculator',
    name: 'File Size Calculator',
    description: 'Calculate file size from bitrate and duration.',
    category: 'Programming',
    iconName: 'FileBox',
  },
  {
    slug: 'color-converter',
    name: 'Color Code Converter',
    description: 'Convert between HEX, RGB, and HSL color codes.',
    category: 'Programming',
    iconName: 'Palette',
  },

  // Geometry & Engineering
  {
    slug: 'circle-calculator',
    name: 'Circle Calculator',
    description: 'Calculate the area and circumference of a circle.',
    category: 'Geometry & Engineering',
    iconName: 'Circle',
  },
  {
    slug: 'triangle-area-calculator',
    name: 'Triangle Area & Perimeter',
    description: 'Calculate the area and perimeter of a triangle.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
  },
  {
    slug: 'rectangle-area-calculator',
    name: 'Rectangle Area & Perimeter',
    description: 'Calculate the area of a rectangle or square.',
    category: 'Geometry & Engineering',
    iconName: 'Ruler',
    formula: "Area = Length * Width"
  },
  {
    slug: 'cylinder-volume-calculator',
    name: 'Cylinder Volume Calculator',
    description: 'Calculate the volume of a cylinder.',
    category: 'Geometry & Engineering',
    iconName: 'Beaker',
  },
  {
    slug: 'sphere-volume-surface-area-calculator',
    name: 'Sphere Volume & Surface Area',
    description: 'Calculate the volume and surface area of a sphere.',
    category: 'Geometry & Engineering',
    iconName: 'Globe',
  },
  {
    slug: 'cone-volume-calculator',
    name: 'Cone Volume Calculator',
    description: 'Calculate the volume of a cone.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
  },
  {
    slug: 'pythagorean-theorem-calculator',
    name: 'Pythagorean Theorem Calculator',
    description: 'Solve for sides of a right triangle.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
    formula: 'a² + b² = c²'
  },
  {
    slug: 'trigonometry-calculator',
    name: 'Trigonometry Calculator',
    description: 'Calculate sin, cos, tan, and more.',
    category: 'Geometry & Engineering',
    iconName: 'Triangle',
  },
  {
    slug: 'beam-deflection-calculator',
    name: 'Beam Deflection Calculator',
    description: 'Calculate the deflection of beams.',
    category: 'Geometry & Engineering',
    iconName: 'Ruler',
  },
  {
    slug: 'torque-calculator',
    name: 'Torque Calculator',
    description: 'Calculate torque from force and distance.',
    category: 'Geometry & Engineering',
    iconName: 'Wind',
  },
  {
    slug: 'ohms-law-calculator',
    name: 'Ohm’s Law Calculator',
    description: 'Calculate voltage, current, and resistance.',
    category: 'Geometry & Engineering',
    iconName: 'Atom',
  },
  {
    slug: 'resistor-color-code-calculator',
    name: 'Resistor Color Code Calculator',
    description: 'Determine resistor values from color codes.',
    category: 'Geometry & Engineering',
    iconName: 'Palette',
  },
  {
    slug: 'capacitor-charge-calculator',
    name: 'Capacitor Charge Calculator',
    description: 'Calculate capacitor charge and discharge times.',
    category: 'Geometry & Engineering',
    iconName: 'Atom',
  },

  // Education & Miscellaneous
  {
    slug: 'gpa-calculator',
    name: 'GPA Calculator',
    description: 'Calculate your Grade Point Average.',
    category: 'Miscellaneous',
    iconName: 'GraduationCap',
    formula: 'Σ(Grade Points * Credits) / Σ(Credits)'
  },
  {
    slug: 'grade-percentage-calculator',
    name: 'Grade Percentage Calculator',
    description: 'Calculate your grade percentage.',
    category: 'Miscellaneous',
    iconName: 'Percent',
  },
  {
    slug: 'reading-time-calculator',
    name: 'Reading Time Calculator',
    description: 'Estimate the time it takes to read a text.',
    category: 'Miscellaneous',
    iconName: 'Book',
  },
  {
    slug: 'typing-speed-calculator',
    name: 'Typing Speed (WPM) Calculator',
    description: 'Measure your words per minute typing speed.',
    category: 'Miscellaneous',
    iconName: 'Keyboard',
  },
  {
    slug: 'loan-affordability-calculator',
    name: 'Loan Affordability Calculator',
    description: 'Estimate how much loan you can afford.',
    category: 'Miscellaneous',
    iconName: 'Landmark',
  },
  {
    slug: 'carbon-footprint-calculator',
    name: 'Carbon Footprint Calculator',
    description: 'Estimate your environmental impact.',
    category: 'Miscellaneous',
    iconName: 'Footprints',
  },
  {
    slug: 'pet-age-calculator',
    name: 'Pet Age Calculator',
    description: 'Calculate your pet\'s age in human years.',
    category: 'Miscellaneous',
    iconName: 'Dog',
  },
];


export const getCalculatorBySlug = (slug: string): Omit<Calculator, 'component'> | undefined => {
  return calculators.find((calculator) => calculator.slug === slug);
};

export const getCalculatorsByCategory = (categorySlug: string) => {
  const category = categories.find(c => c.slug === categorySlug);
  if (!category) return [];
  return calculators.filter(c => c.category === category.name);
}
