
"use client";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { FAQPage, WithContext } from "schema-dts";

const jsonLd: WithContext<FAQPage> = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is a carbon footprint?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. This calculator provides a simplified estimate based on common daily activities.",
      },
    },
    {
      "@type": "Question",
      name: "Why is this an estimate?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Calculating a precise carbon footprint is very complex. The actual impact depends on factors like your local power grid's mix of renewable vs. fossil fuels, your car's specific fuel efficiency, and the complex supply chains of the food you eat. This tool uses global and national averages to provide a general but insightful estimate.",
      },
    },
    {
      "@type": "Question",
      name: "How can I reduce my carbon footprint?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "There are many ways to reduce your footprint. In transport, consider using public transit, cycling, or walking. In the home, reduce energy consumption by using energy-efficient appliances, improving insulation, and turning off lights. Dietarily, reducing consumption of red meat, especially beef and lamb, can significantly lower your food-related emissions.",
      },
    },
  ],
};

export default function AboutCarbonFootprintCalculator() {
  return (
    <Card>
      <CardHeader>
        <CardTitle as="h2">About the Carbon Footprint Calculator</CardTitle>
      </CardHeader>
      <CardContent className="prose dark:prose-invert max-w-none">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <p>
          The Carbon Footprint Calculator gives a simple estimate of the
          greenhouse gas emissions from your daily activities. It helps you see
          your environmental impact by looking at three key areas:
          transportation, household energy, and diet.
        </p>

        <h3>How to Use the Carbon Footprint Calculator</h3>
        <ol>
          <li>
            **Daily Commute:** Enter the one-way distance of your daily commute
            and select your main mode of transport.
          </li>
          <li>
            **Household Energy:** Input your average monthly electricity usage
            in kilowatt-hours (kWh). You can usually find this on your utility
            bill.
          </li>
          <li>
            **Diet:** Choose the dietary pattern that best matches your own.
          </li>
        </ol>
        <p>
          The calculator will estimate your total monthly carbon footprint in
          tonnes of CO₂ equivalent (CO₂e).
        </p>

        <h3>Carbon Footprint FAQs</h3>
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="item-1">
            <AccordionTrigger>What is a carbon footprint?</AccordionTrigger>
            <AccordionContent>
              A carbon footprint is the total amount of greenhouse gases
              generated by our actions. This includes carbon dioxide and
              methane. This calculator gives a simple estimate based on common
              daily activities.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>Why is this an estimate?</AccordionTrigger>
            <AccordionContent>
              Finding a precise carbon footprint is very complex. The actual
              impact depends on many factors. These include your local power
              grid's energy sources, your car's fuel efficiency, and the supply
              chains of your food. This tool uses averages to provide a general
              but useful estimate.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>
              How can I reduce my carbon footprint?
            </AccordionTrigger>
            <AccordionContent>
              There are many ways to reduce your footprint. For transport, try
              using public transit, cycling, or walking. At home, reduce energy
              use with efficient appliances and by turning off lights. As for
              diet, eating less red meat, like beef and lamb, can significantly
              lower your food-related emissions.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </CardContent>
    </Card>
  );
}
